CC = g++
CCFLAGS = -Wall -g

Assign3: Assign3.o
	$(CC) -o z1747708_A3 $(CCFLAGS) Assign3.o

Assign3.o: Assign3.cpp
	$(CC) -c $(CCFLAGS) Assign3.cpp

run:
	./z1747708_A3

clean:
	-rm Assign3.o z1747708_A3
